name: Daily Send

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/sport-notify-bot-ci:latest
    name: Send daily message
    concurrency:
      group: daily-send
      cancel-in-progress: false
    env:
      TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      BROWSER_PATH: /usr/bin/chromium-browser
    steps:
      - name: Download source code directly
        run: |
          cd /tmp
          wget -qO repo.tar.gz https://api.github.com/repos/${{ github.repository }}/tarball/${{ github.ref_name }}
          mkdir -p /work
          tar -xzf repo.tar.gz -C /work --strip-components=1
          cd /work
          ls -la
          
      - name: Install gems directly
        run: |
          cd /work
          gem install nokogiri -v ">= 1.15" --platform=ruby --no-document
          gem install base64 -v "~> 0.2.0" --no-document
          gem install dotenv -v "~> 3.1.8" --no-document
          gem install faraday -v "~> 2.13.0" --no-document
          gem install ferrum -v "~> 0.16" --no-document
      
      - name: Run sender
        working-directory: /work
        run: |
          ruby -e 'puts "Ruby версия: #{RUBY_VERSION}"'
          ruby -I lib exe/sport_notify_bot send