name: Daily Send

on:
  schedule:
    - cron: "0 8 * * *"  # 08:00 UTC == 13:00 Asia/Yekaterinburg
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    name: Send daily message
    concurrency:
      group: daily-send
      cancel-in-progress: false
    env:
      TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'
          bundler-cache: true

      - name: Install Chromium (for FlashscoreParser)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          echo "BROWSER_PATH=$(which chromium-browser)" >> "$GITHUB_ENV"

      - name: Run sender
        env:
          BROWSER_PATH: ${{ env.BROWSER_PATH }}
        run: |
          bundle install --quiet
          bundle exec ./exe/sport_notify_bot send