name: Daily Send

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/sport-notify-bot-ci:latest
    name: Send daily message
    concurrency:
      group: daily-send
      cancel-in-progress: false
    env:
      TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      BROWSER_PATH: /usr/bin/chromium-browser
    steps:
      - uses: actions/checkout@v3
      - name: Mark workspace as safe for git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global --add safe.directory "/__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}"
      - name: Prepare bundler
        run: |
          bundle config set path 'vendor/bundle'
          bundle config set without 'development test'
          bundle config set force_ruby_platform true
          bundle lock --add-platform x86_64-linux x86_64-linux-gnu x86_64-linux-musl || true
      - name: Bundle install
        env:
          BUNDLE_FORCE_RUBY_PLATFORM: "true"
        run: bundle install --jobs 4 --retry 3
      - name: Run sender
        run: bundle exec ./exe/sport_notify_bot send