name: Daily Send

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/sport-notify-bot-ci:latest
    name: Send daily message
    concurrency:
      group: daily-send
      cancel-in-progress: false
    env:
      TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      BROWSER_PATH: /usr/bin/chromium-browser
      BUNDLE_FORCE_RUBY_PLATFORM: "true"
      BUNDLE_BUILD__NOKOGIRI: "--use-system-libraries"
    steps:
      - uses: actions/checkout@v3
      - name: Fix git safe.directory
        run: git config --global --add safe.directory '*'
      - name: Prepare bundler
        run: |
          bundle config set path 'vendor/bundle'
          bundle config set without 'development test'
          bundle config set force_ruby_platform true
      - name: Bundle install
        run: bundle install --jobs 4 --retry 3 --quiet
      - name: Run sender
        run: bundle exec ./exe/sport_notify_bot send