name: Daily Send

on:
  schedule:
    - cron: "0 8 * * *"  # 08:00 UTC == 13:00 Asia/Yekaterinburg
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/sport-notify-bot-ci:latest
    name: Send daily message
    concurrency:
      group: daily-send
      cancel-in-progress: false
    env:
      TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      BROWSER_PATH: /usr/bin/chromium-browser
    steps:
      - uses: actions/checkout@v3
      - name: Bundle install
        run: bundle install --quiet
      - name: Run sender
        run: bundle exec ./exe/sport_notify_bot send